<?php

namespace AppBundle\Repository;

/**
 * MutuelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MutuelleRepository extends \Doctrine\ORM\EntityRepository
{
}
